FROM alpine:3.16.3
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG S6_VERSION='3.1.2.1'
ARG S6_ARCH='x86_64'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    S6_VERSION="${S6_VERSION}" \
    S6_ARCH="${S6_ARCH}"

RUN set -x && \
    apk --no-cache upgrade && \
    mkdir /tmp/s6 && \
    wget https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-noarch.tar.xz -O /tmp/s6/s6-overlay-noarch.tar.xz && \
    wget https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-noarch.tar.xz.sha256 -O /tmp/s6/s6-overlay-noarch.tar.xz.sha256 && \
    wget https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${S6_ARCH}.tar.xz -O /tmp/s6/s6-overlay-${S6_ARCH}.tar.xz && \
    wget https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${S6_ARCH}.tar.xz.sha256 -O /tmp/s6/s6-overlay-${S6_ARCH}.tar.xz.sha256 && \
    cd /tmp/s6 && \
    sha256sum -c *.sha256 && \
    tar -Jxpf s6-overlay-noarch.tar.xz -C / && \
    tar -Jxpf s6-overlay-${S6_ARCH}.tar.xz -C / && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*

### Start Program
ENTRYPOINT ["/init"]
