FROM alpine:3.21.0
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG S6_VERSION='3.2.0.2'
ARG S6_ARCH='x86_64'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    S6_BEHAVIOUR_IF_STAGE2_FAILS='2' \
    S6_VERSION="${S6_VERSION}" \
    S6_ARCH="${S6_ARCH}"

COPY root/ /

RUN set -x && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=base-deps \
      shadow \
    && \
    mkdir /tmp/s6 && \
    wget https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-noarch.tar.xz -O /tmp/s6/s6-overlay-noarch.tar.xz && \
    wget https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-noarch.tar.xz.sha256 -O /tmp/s6/s6-overlay-noarch.tar.xz.sha256 && \
    wget https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${S6_ARCH}.tar.xz -O /tmp/s6/s6-overlay-${S6_ARCH}.tar.xz && \
    wget https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${S6_ARCH}.tar.xz.sha256 -O /tmp/s6/s6-overlay-${S6_ARCH}.tar.xz.sha256 && \
    cd /tmp/s6 && \
    sha256sum -c *.sha256 && \
    tar -Jxpf s6-overlay-noarch.tar.xz -C / && \
    tar -Jxpf s6-overlay-${S6_ARCH}.tar.xz -C / && \
    useradd -u 12345 -m -U -s /sbin/nologin appuser && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*

### Start Program
ENTRYPOINT ["/init"]
