#!/command/with-contenv sh

tz=${TZ:-"Europe/Brussels"}

apk add --no-cache --virtual=timezone-deps tzdata

if [ -f /usr/share/zoneinfo/${tz} ]; then
  cp /usr/share/zoneinfo/${tz} /etc/localtime
  echo "${tz}" > /etc/timezone
else
  echo "[ERROR] wrong timezone provided, please check env TZ"
fi

apk del --no-cache --purge timezone-deps
